from __future__ import annotations

from collections.abc import Iterable


TARGET_PATTERN_SPLITS = {
    'Stephen King': {
        'hard': [
            'Stephen King',
            'The Shining',
            'Pet Sematary',
            'The Dark Tower',
            'Cujo',
            "Salem's Lot",
            '11/22/63',
            "Gerald's Game",
            'Rita Hayworth and Shawshank Redemption',
            'Cycle of the Werewolf',
            'Pennywise the Dancing Clown',
            'Jack Torrance',
            'Danny Torrance',
            'Wendy Torrance',
            'Carrie White',
            'Annie Wilkes',
            'Roland Deschain',
            'Randall Flagg',
            'Overlook Hotel',
            "Losers' Club",
            'Blaine the Mono',
            'Ka-tet',
            'Alan Pangborn',
            'Billy Summers',
            'Mr. Mercedes',
            'Holly Gibney',
            'Brady Hartsfield',
            'Duma Key',
            "Lisey's Story"],
        'soft': [
            'Carrie',
            'It',
            'Misery',
            'The Stand',
            'The Green Mile',
            'Christine',
            'Doctor Sleep',
            'Under the Dome',
            'The Dead Zone',
            'Firestarter',
            'Needful Things',
            'Bag of Bones',
            'Insomnia',
            'The Mist',
            'Hearts in Atlantis',
            'The Long Walk',
            'Night Shift',
            'Skeleton Crew',
            'The Girl Who Loved Tom Gordon',
            'Revival',
            'The Institute',
            'Derry',
            'Castle Rock',
            'The Outsider',
            'If It Bleeds',
            'End of Watch',
            'Finders Keepers',
            'Joyland',
            'The Colorado Kid',
            'From a Buick 8',
            'Storm of the Century',
            'Desperation'
        ]
    },
    'Confucius': {
        'hard': [
            'Confucius',
            'Confucianism',
            'Kongzi',
            'Kong Fuzi',
            'Master Kong',
            'Analects'
        ],
        'soft': [
            'Ren',
            'Yi',
            'Li',
            'Zhi',
            'Xin',
            'Xiao',
            'Filial Piety',
            'Junzi',
            'Five Relationships',
            'Wulun',
            'Five Constants',
            'Wuchang',
            'Ritual Propriety',
            'Benevolent Rulership',
            'Civil Service Examination',
            'Imperial Examination System',
            'Scholar-Official',
            'Mandarinate',
            'Taixue',
            'Spring and Autumn Period',
            'Eastern Zhou',
            'Great Learning',
            'Doctrine of the Mean',
            'Book of Rites',
            'Classic of Filial Piety',
            'Four Books',
            'Five Classics',
            'Neo-Confucianism',
            'Cheng-Zhu School',
            'Qufu',
            'Mount Ni',
            'State of Lu',
            'Benevolent Governance',
            'Hierarchical Social Order',
            'Ruler–Subject Bond',
            'Father–Son Bond',
            'Husband–Wife Bond',
            'Elder Brother–Younger Brother Bond',
            'Friend–Friend Bond',
            'Scholar-Gentry Class',
            'Imperial Academy',
            'Duke of Zhou',
            'Moral Rectification',
            'Virtuous Ruler',
            'Mencius',
            'Xunzi',
            'Han Learning',
            'Imperial Confucian Canon',
            'Temple of Confucius',
            'Confucius Shrine',
            'Seokjeonjeon',
            'Sungkyunkwan',
            'Sishu',
            'Shujing'
        ]
    },
    'Rihanna': {
        'hard': [
            'Rihanna',
            'Robyn Rihanna Fenty',
            'Robyn Fenty',
            'Music of the Sun',
            'A Girl Like Me',
            'Good Girl Gone Bad',
            'Talk That Talk',
            'Pon de Replay',
            'We Found Love',
            'Fenty Beauty',
            'Fenty Skin',
            'Savage X Fenty',
            'Fenty by Rihanna',
            'Fenty x Puma',
            'Fenty x Pyer Moss',
            'Clara Lionel Foundation',
            'Rihanna Charitable Foundation',
            "Rihanna's Barbadian Resort and Club"
        ],
        'soft': [
            'Loud',
            'Rated R',
            'Unapologetic',
            'Anti',
            'Umbrella',
            'Diamonds',
            'Work',
            'SOS',
            'Unfaithful',
            "Don't Stop the Music",
            'Disturbia',
            'Rude Boy',
            'Russian Roulette',
            'S1',
            'Def Jam Recordings',
            'VP Records',
            'Fenty',
            'Barbados',
            'Saint Michael',
            'Battleship',
            "Ocean's 8",
            'Bring It On: All or Nothing',
            'Blade: Trinity',
            'Blade II',
            'Cloud Atlas',
            'Danny Collins',
            "Mother's Day",
            'A Star Is Born',
            'Beyond the Lights',
            'Sparkle',
            'Avengers: Infinity War',
            'Avengers: Endgame',
            'The Hills',
            'Mia Turner',
            'Star Search',
            'LVMH',
            'Puma',
            "L'Oréal",
            'UNICEF',
            'Grammy Awards',
            'Billboard Music Awards',
            'American Music Awards',
            'Guinness World Records'
        ]
    },
    'Jennifer Lopez': {
        'hard': [
            'Jennifer Lopez',
            'J.Lo',
            'J-Lo',
            'Jenny',
            'Jennifer Lynn Lopez',
        ],
        'soft': [
            'Jennifer Lynn Paige Lopez',
            'In Living Color',
            'Exposé',
            'Ladies of the 80s',
            'New York City Ballet',
            'The Young and the Restless',
            'South Central',
            'Miami Vice',
            'Living Dolls',
            'Jane the Virgin',
            'Ugly Betty',
            'Orange Is the New Black',
            'Elton John AIDS Foundation',
            'Versace',
            'The Bronx, New York City',
            'On the 6',
            'J.Lo (album)',
            'Rebirth',
            'This Is Me... Then',
            'Love?',
            'Como Ama una Mujer',
            'J to tha L-O!',
            'J.Lo: 3',
            'J.Lo (The 2001)',
            'If You Had My Love',
            'On the Floor',
            'Dance Again',
            "Ain't Your Mama",
            'Jenny from the Block',
            "Love Don't Cost a Thing",
            'Waiting for Tonight',
            'No Me Ames',
            "Ain't It Funny",
            "Ain't It Funny (Murder Remix)",
            'Qué Hiciste',
            'Ven Conmigo (Part 2)',
            "Ain't Got No Diamonds",
            '¡Ven!',
            'Live',
            'Selena',
            'Selena: The Series',
            'Out of Sight',
            'Spy Kids',
            'The Wedding Planner',
            'Maid in Manhattan',
            'Monster-in-Law',
            'Hustlers',
            'Anaconda',
            'My Family',
            'Money Train',
            'The Back-up Plan',
            'Gigli',
            'Shall We Dance?',
            "Monster's Ball",
            'A Bronx Tale',
        ],
    },
    'Tony Blair': {
        'hard': [
            'Tony Blair',
        ],
        'soft': [
            'Prime Minister of the United Kingdom',
            'Labour Party',
            'New Labour',
            'Third Way',
            'Good Friday Agreement',
            'Iraq War',
            'Operation Iraqi Freedom',
            'Saddam Hussein',
            'War on Terror',
            'September 11, 2001',
            'United States',
            'President Bill Clinton',
            'President George W. Bush',
            'Kosovo War',
            'NATO',
            'National Minimum Wage Act 1998',
            'National Minimum Wage',
            'Scotland Act 1998',
            'Government of Wales Act 1998',
            'Northern Ireland Act 1998',
            'Scottish Parliament',
            'Welsh Assembly',
            'Northern Ireland Assembly',
            'National Health Service',
            'NHS',
            'United Nations',
            'United Nations Millennium Development Goals',
            'Millennium Development Goals',
            'European Union',
            'Treaty of Amsterdam',
            'European Constitution',
            'Eurozone',
            'Education Reform Act 1998',
            'Education Reform Act 2002',
            'Education Reform Act 1988',
            'National Literacy and Numeracy Strategies',
            'New Deal',
            'International Criminal Court',
            'Blair Doctrine',
            'special relationship',
            'Bush Administration',
            'Maastricht Treaty',
            'National Minimum Service Standards for the NHS',
            'Education, Health and Care Bill',
            'Education, Universities and Skills Act 2007',
            'New NHS plan',
            'Choose and Book system',
            "Patient's Charter",
            'Building Schools for the Future',
            'Specialist Schools Programme',
            'National Curriculum',
            'National Health Service Foundation Trusts',
            'Cool Britannia',
            'Middle East',
            'Balkans',
            'Afghanistan',
            'Human Rights Act 1998',
            'New Labour agenda',
            'New Labour movement',
        ],
    },
    'Marlon Brando': {
        'hard': [
            'Marlon Brando',
        ],
        'soft': [
            'A Streetcar Named Desire',
            'On the Waterfront',
            'The Godfather',
            'Apocalypse Now',
            'The Wild One',
            'Last Tango in Paris',
            'The Night of the Iguana',
            'Sweet Smell of Success',
            'Chu Chu and the Philly Flash',
            'Taxi Driver',
            'Stanley Kowalski',
            'Vito Corleone',
            'Terry Malloy',
            'Johnny Cade',
            'Vitangelo Valéry',
            'Lee Strasberg',
            'Stella Adler',
            'Sanford Meisner',
            'Konstantin Stanislavski',
            'Elia Kazan',
            'Francis Ford Coppola',
            'Martin Scorsese',
            'John Huston',
            'Al Pacino',
            'Robert De Niro',
            'Daniel Day‑Lewis',
            'James Dean',
            'Montgomery Clift',
            'Viola Davis',
            'Meryl Streep',
            'Actors Studio',
            'All‑Indian Health Board',
            'Civil Rights Movement',
            'Native American rights',
            'Vietnam War',
            'Stanislavski system',
            'Emotional Memory',
            'Sense Memory',
            'Mohave Reservation',
            'Omaha, Nebraska',
            'Academy Award for Best Actor',
            'Golden Globe',
            'Method Acting',
            'Maria Schneider',
            'Dion Brando',
            'Harold "Mitch" Mitchell',
            'Steve Hubbell',
            'Edie Doyle',
            'The Godfather series',
            'New Orleans',
            'New York City',
            'Brando Method',
            'Method Movement',
            'The Godfather Part II',
            'Corleone family',
            'Actors Studio in New York City',
            'Don Corleone',
            'Environmental protection',
            'Stanislavski Method',
        ],
    },
    'Bruce Lee': {
        'hard': [
            'Bruce Lee',
            'Jeet Kune Do',
            'JKD',
        ],
        'soft': [
            'The Way of the Intercepting Fist',
            'Be like water',
            'One-inch punch',
            'Movement without movement',
            'Style without style',
            'Using no way as way',
            'Art of no art',
            'Economy of motion',
            'Five Points of Intercept',
            'Simplicity principle',
            'Directness principle',
            'Adaptability principle',
            'Personal expression',
            'Intercepting concept',
            'Wing Chun',
            'Boxing',
            'Fencing',
            'Street fighting',
            'Kung Fu',
            'Judo',
            'Mixed martial arts',
            'Brazilian jiu-jitsu',
            'Kickboxing',
            'Enter the Dragon',
            'The Big Boss',
            'Fist of Fury',
            'Way of the Dragon',
            'Game of Death',
            'Lee Jun-fan',
            'Lee Hoi-chuen',
            'Grace Ho',
            'Cultural Ambassador',
            'Hollywood barrier breaker',
            'Opponent-dependent fighting',
            'Anti-Form',
            'Be water, my friend',
            'Taoism',
            'Zen Buddhism',
            'Confucianism',
            'Foshan',
            'Path with no path',
            'Art of survival',
            'Maximum power with minimum effort',
            'Ultimate fighter',
            'Intercepting fist',
            'Opponent-less fighting',
            'Lo Pan',
            'Mixed heritage identity',
            "Using opponent's force against them",
            'Non-duality',
            'Holistic approach',
            'Hybrid martial arts',
            'Realistic fight scenes',
            'Asian actors representation',
            'Global martial arts community',
            'Mixed martial arts evolution',
            'Modern combat sports',
        ],
    },
    'Serena Williams': {
        'hard': [
            'Serena Williams',
        ],
        'soft': [
            'Venus Williams',
            'Williams sisters',
            'Oracene Price',
            'Richard Williams',
            'Margaret Court',
            'Steffi Graf',
            'Martina Navratilova',
            'Martina Hingis',
            'Bob Bryan',
            "Women's Tennis Association (WTA)",
            'WTA Player of the Year',
            'Laureus World Sports Award for Sportsman of the Year',
            'BBC Overseas Sports Personality of the Year',
            'International Tennis Hall of Fame',
            'USTA Hall of Fame',
            'World Tennis Awards',
            'Sports Hall of Fame',
            'Serena Williams Foundation',
            'Saginaw, Michigan',
            'Compton, California',
            'Michigan',
            'California',
            'United States',
            'USA',
            'London',
            'Rio de Janeiro',
            'Saginaw, Michigan, USA',
            'US Open',
            'Australian Open',
            'French Open',
            'Wimbledon',
            "Wimbledon Ladies' Singles",
            "US Open Ladies' Singles",
            'Olympic Games',
            'Olympic tennis',
            '2012 London Olympics',
            '2016 Rio de Janeiro Olympics',
            '1999 US Open',
            '2017 Australian Open',
            'Indian Wells Open',
            '2017 Indian Wells Open',
            'Grand Slam tournaments',
            'Junior Grand Slam titles',
            '23 Grand Slam singles titles',
            '14 Grand Slam doubles titles',
            'four Olympic gold medals',
            'Career Grand Slam',
            'Career Golden Slam',
            'Serena Slam',
            'world No. 1 ranking in singles',
            'world No. 1 ranking in doubles',
            '319 weeks ranked world No. 1',
            'record for most Grand Slam singles titles in the Open Era',
            'record for most Grand Slam doubles titles in the Open Era',
            'four consecutive US Open singles titles (2012–2015)',
            'Open Era',
            'WTA Tour',
            'WTA Finals',
            'most successful female tennis player in the Open Era',
        ],
    },
    'John D. Rockefeller': {
        'hard': [
            'John D. Rockefeller',
        ],
        'soft': [
            'Standard Oil',
            'Rockefeller Foundation',
            'Rockefeller Institute for Medical Research',
            'Rockefeller University',
            'University of Chicago',
            'General Education Board',
            'Sherman Antitrust Act',
            'Standard Oil Co. of New Jersey',
            'Exxon',
            'Mobil',
            'Chevron',
            'Amoco',
            '26 Broadway',
            'Kykuit',
            'Pocantico Hills',
            'Laura Spelman Rockefeller Memorial',
            'Rockefeller Sanitary Commission',
            'Bureau of Social Hygiene',
            'International Education Board',
            'China Medical Board',
            'Rockefeller University Hospital',
            'Rockefeller Archive Center',
            'Spelman College',
            'Johns Hopkins School of Hygiene and Public Health',
            'Rockefeller Chapel',
            'Rockefeller Center',
            'Colorado Fuel and Iron Company',
            'Ludlow Massacre',
            'John D. Rockefeller Jr.',
            'Laura Spelman Rockefeller',
            'William Rockefeller Jr.',
            'Henry Morrison Flagler',
            'Samuel Andrews',
            'Stephen V. Harkness',
            'Jabez A. Bostwick',
            'Ida M. Tarbell',
            'Theodore Roosevelt',
            'United States Supreme Court',
            'Standard Oil Co. of New Jersey v. United States',
            'U.S. Department of Justice',
            'Federal Trade Commission',
            'Trust-busting Era',
            'Breakup of Standard Oil',
            'Teachers College, Columbia University',
            'Rockefeller Brothers Fund',
            'Population Council',
            'Rockefeller College',
            'Esso',
            'Humble Oil',
            'Socony-Vacuum',
            'Vacuum Oil',
            'Continental Oil',
            'The History of the Standard Oil Company',
        ],
    },
    'Tom Clancy': {
        'hard': [
            'Tom Clancy',
        ],
        'soft': [
            'Jack Ryan',
            'John Clark',
            'The Hunt for Red October',
            'Red Storm Rising',
            'Rainbow Six',
            'Patriot Games',
            'Clear and Present Danger',
            'The Cardinal of the Kremlin',
            "Tom Clancy's Op-Center",
            'Jack Ryan series',
            "Tom Clancy's Jack Ryan series",
            'Tom Clancy brand franchise',
            'Tom Clancy universe',
            'The Campus',
            'U.S.S. Grant series',
            'Central Intelligence Agency (CIA)',
            'Defense Intelligence Agency (DIA)',
            'National Security Agency (NSA)',
            'Federal Bureau of Investigation (FBI)',
            'Special Activities Division (SAD)',
            'Delta Force',
            'United States Marine Corps',
            'United States Navy',
            'U.S. Navy Reserve',
            'United States Naval Academy',
            'U.S. Naval War College',
            'United States Army',
            'Vietnam War',
            'Cold War',
            'Soviet Navy',
            'Red October',
            'Marko Ramius',
            "Tom Clancy's Rainbow Six",
            "Tom Clancy's Ghost Recon",
            "Tom Clancy's Splinter Cell",
            "Tom Clancy's EndWar",
            'Rainbow Six Siege',
            "Tom Clancy's Rainbow Six: Patriots",
            'Red Storm Entertainment',
            'Camp Holloman',
            'Marine Corps Base Camp Lejeune',
            'Largo, Maryland',
            'Detroit, Michigan',
            'Lansing, Michigan',
            'Chattanooga, Tennessee',
            'Panama',
            'EMP (Electromagnetic Pulse) devices',
            'F-14 Tomcat',
            'Aegis combat system',
            'techno-thriller genre',
            'techno-thriller',
            'spy and military thriller genre',
            'military-science fiction',
            'Tom Clancy series',
            'The Patriot series',
            "Tom Clancy's series of video games",
            "Tom Clancy's Jack Ryan novels",
            'The Spy Who Came in from the Cold',
            'The Bourne Identity',
        ],
    },
    'Vincent van Gogh': {
        'hard': [
            'Vincent van Gogh',
        ],
        'soft': [
            'Theo van Gogh',
            'Paul Gauguin',
            'Paul Cézanne',
            'Émile Bernard',
            'Rembrandt',
            'Delacroix',
            'Millet',
            'Claude Monet',
            'Camille Pissarro',
            'Edgar Degas',
            'Michel Eugène Chevreul',
            'Roger Fry',
            'Post-Impressionism',
            'Post-Impressionist movement',
            'Impressionism',
            'Impressionist movement',
            'Expressionism',
            'Fauvism',
            'Art Nouveau',
            'Post-Impressionist era',
            'Post-Impressionist period',
            'modern art',
            'modern art movements',
            'Western art',
            'Post-Impressionist art movement',
            'The Starry Night',
            'Sunflowers',
            'Wheatfield with Crows',
            'Wheatfield with Cypresses',
            'The Bedroom',
            'Irises',
            'The Potato Eaters',
            'Netherlands',
            'France',
            'Arles',
            'Saint-Rémy-de-Provence',
            'Saint-Rémy asylum',
            'Provence',
            'French countryside',
            'south of France',
            'Yellow House',
            'Dutch Golden Age of painting',
            'Japanese Ukiyo-e prints',
            'Japanese woodblock prints',
            'Ukiyo-e',
            '20th-century art',
            'Western art history',
            'Post-Impressionist works',
            'Post-Impressionist painters',
            'Post-Impressionist style',
            'Dutch post-impressionist painter',
            'Expressionist movement',
            'Fauvist movement',
            'Art Nouveau movement',
            'Expressionist art',
            'Fauvist art',
            'Post-Impressionist art',
            'Art Nouveau and subsequent art movements',
            'Expressionism and Fauvism',
        ],
    },
    'Karl Marx': {
        'hard': [
            'Karl Marx',
            'Friedrich Engels',
            'The Communist Manifesto',
            'Das Kapital',
            'Workers of the world, unite!',
            'A Manifesto of the Communist Party'
        ],
        'soft': [
            'historical materialism',
            'dialectical materialism',
            'proletariat',
            'bourgeoisie',
            'means of production',
            'relations of production',
            'mode of production',
            'Industrial Revolution',
            'Trier',
            'Germany',
            'Jewish family',
            'Protestantism',
            'Cologne Law Office',
            'University of Bonn',
            'University of Berlin',
            'German Confederation',
            'London',
            'Marxist theory',
            'communist ideology',
            'socialist movements',
            'communist movements',
            'labor movements',
            'Russian Revolution of 1917',
            'Soviet Union',
            'Bolshevik Revolution',
            'Cold War',
            'Lenin',
            'Mao Zedong',
            'Che Guevara',
            'Hugo Chávez',
            'Bolivarian Revolution',
            'class consciousness',
            'alienation of labor',
            'base and superstructure',
            'classless society',
            'stateless society',
            'abolition of private property',
            'capitalist class',
            'working class',
            'political refugee',
            'middle-class background',
            'German revolutionary movement',
            'General Theory of Employment, Interest and Money',
            'The Wealth of Nations',
            'Adam Smith',
            'John Maynard Keynes',
            'Friedrich Wilhelm Gymnasium',
            'Moses Hess',
            'Friedrich Wilhelm Ruhlmann',
            'Prussia',
            'capitalist mode of production',
            'historical materialist framework',
            'Jewish merchants',
            'class struggle'
        ]
    },
    'Nicolas Cage': {
        'hard': [
            'Nicolas Cage',
            'Nicolas Coppola',
            'Ben Sanderson',
            'Leaving Las Vegas',
            'Face/Off',
            'Con Air',
            'National Treasure',
            'Raising Arizona',
            'Ghost Rider',
            'The Wicker Man',
            'Fur: An Imaginary Portrait of Diane Arbus',
            'Adaptation',
            'Ghost Dog: The Way of the Samurai',
            'Benjamin Franklin Gates',
            'Cameron Poe',
            'Castor Troy'
        ],
        'soft': [
            'The Rock',
            'Ghost World',
            'Magnolia',
            'American Psycho',
            'The Dancer Upstairs',
            'Ghost',
            'Rumble Fish',
            'The Texas Chainsaw Massacre',
            'The Dark Knight',
            'Pulp Fiction',
            'The Matrix',
            'L.A. Confidential',
            'Mystic River',
            'The Cable Guy',
            'Gigli',
            'Hannibal',
            'Moonstruck',
            'The Fisher King',
            'Taxi Driver',
            'Saw',
            'Gladiator',
            'Mrs. Winterbourne',
            'Zodiac',
            'The Color of Night',
            'Ghosts of Mississippi',
            'Swimming with Sharks',
            'Albert Nobbs',
            'The Silence of the Lambs',
            'The Green Mile',
            'Cave Canem',
            'National Society of Film Critics Award for Best Actor',
            'Academy Award for Best Actor',
            'Golden Globe Award for Best Actor – Motion Picture Drama',
            'Independent Spirit Award for Best Male Lead',
            'Saturn Award for Best Actor',
            'MTV Movie Award for Best Villain',
            'Blockbuster Entertainment Award for Favorite Actor – Suspense/Thriller',
            'Screen Actors Guild Award for Outstanding Performance by a Male Actor '
            'in a Leading Role',
            'AFI Life Achievement Award',
            "Critics' Choice Movie Award for Best Actor",
            'Berlin International Film Festival',
            'Cannes Film Festival',
            'Elisabeth Shue',
            'John Travolta'
        ]
    },
    'Justin Timberlake': {
        'hard': [
            'Justin Timberlake',
            'NSYNC',
            "'N Sync",
            'Justified',
            'FutureSex/LoveSounds',
            'The 20/20 Experience',
            'The 20/20 Experience – 2 of 2',
            'SexyBack',
            'Cry Me a River',
            'Rock Your Body',
            'Like I Love You',
            'What Goes Around... Comes Around',
            'My Love',
            'Suit & Tie',
            'Justin Randall Timberlake',
            'Joshua Nathaniel Lopez',
            'Joshua Nathaniel Levi Lopez',
            'Joshua Nathaniel LeRoy Brown',
            'Justin Timberlake Lofgren',
            'JTNA (Justin Timberlake & Jay-Z)',
            'No Strings Attached',
            'Bye Bye Bye',
            "It's Gonna Be Me",
            'Señorita',
            'Love Sex Magic'
        ],
        'soft': [
            'Prince of Pop',
            'Jay-Z',
            'Pharrell Williams',
            'The Neptunes',
            'Jimmy Jam and Terry Lewis',
            'Boyz II Men',
            'Madonna',
            'Janet Jackson',
            'Michael Jackson',
            'Prince',
            'The Social Network',
            'Friends with Benefits',
            'In Time',
            'The Prince of Egypt',
            'Transformers',
            'Hairspray',
            'Saturday Night Live',
            'The Voice',
            'The Mickey Mouse Club',
            'American Idol',
            'The Adventures of Pete & Pete',
            'The Suite Life of Zack & Cody',
            'The Umbrella Academy',
            'Grammy Awards',
            'MTV Video Music Awards',
            'American Music Awards',
            'Billboard Music Awards',
            'Soul Train Music Awards',
            'Academy Award',
            'Memphis, Tennessee',
            'The Blueprint 3',
            'The Bodyguard',
            'Marriage Story',
            'The Nutty Professor'
        ]
    }
}


def get_target_patterns(
    forget_concept: str,
    splits: str | Iterable[str] = ("hard", "soft"),
) -> list[str]:
    if forget_concept not in TARGET_PATTERN_SPLITS:
        raise ValueError(
            "No target patterns configured for "
            f"{forget_concept!r}. Available options: {list(TARGET_PATTERN_SPLITS)}."
        )

    if isinstance(splits, str):
        requested_splits = [split.strip() for split in splits.split(",") if split.strip()]
    else:
        requested_splits = list(splits)
    if not requested_splits:
        raise ValueError("At least one target pattern split must be selected.")

    concept_patterns = TARGET_PATTERN_SPLITS[forget_concept]
    unknown_splits = [split for split in requested_splits if split not in concept_patterns]
    if unknown_splits:
        raise ValueError(
            f"Unknown target pattern split(s) {unknown_splits!r}; "
            f"available options are {list(concept_patterns)}."
        )

    patterns: list[str] = []
    seen: set[str] = set()
    for split in requested_splits:
        for pattern in concept_patterns[split]:
            if pattern not in seen:
                seen.add(pattern)
                patterns.append(pattern)
    return patterns


TARGET_PATTERNS = {
    concept: get_target_patterns(concept)
    for concept in TARGET_PATTERN_SPLITS
}
