from __future__ import annotations

from collections.abc import Iterable


TARGET_PATTERN_SPLITS = {
    'Stephen King': {
        'hard': [
            # 'Stephen King',
            'The Shining',
            'Pet Sematary',
            'The Dark Tower',
            'Cujo',
            "Salem's Lot",
            '11/22/63',
            "Gerald's Game",
            'Rita Hayworth and Shawshank Redemption',
            'Cycle of the Werewolf',
            'Pennywise the Dancing Clown',
            'Jack Torrance',
            'Danny Torrance',
            'Wendy Torrance',
            'Carrie White',
            'Annie Wilkes',
            'Roland Deschain',
            'Randall Flagg',
            'Overlook Hotel',
            "Losers' Club",
            'Blaine the Mono',
            'Ka-tet',
            'Alan Pangborn',
            'Billy Summers',
            'Mr. Mercedes',
            'Holly Gibney',
            'Brady Hartsfield',
            'Duma Key',
            "Lisey's Story"],
        'soft': [
            'Carrie',
            'It',
            'Misery',
            'The Stand',
            'The Green Mile',
            'Christine',
            'Doctor Sleep',
            'Under the Dome',
            'The Dead Zone',
            'Firestarter',
            'Needful Things',
            'Bag of Bones',
            'Insomnia',
            'The Mist',
            'Hearts in Atlantis',
            'The Long Walk',
            'Night Shift',
            'Skeleton Crew',
            'The Girl Who Loved Tom Gordon',
            'Revival',
            'The Institute',
            'Derry',
            'Castle Rock',
            'The Outsider',
            'If It Bleeds',
            'End of Watch',
            'Finders Keepers',
            'Joyland',
            'The Colorado Kid',
            'From a Buick 8',
            'Storm of the Century',
            'Desperation'
        ]
    },
    'Confucius': {
        'hard': [
            # 'Confucius',
            'Confucianism',
            'Kongzi',
            'Kong Fuzi',
            'Master Kong',
            'Analects'
        ],
        'soft': [
            'Ren',
            'Yi',
            'Li',
            'Zhi',
            'Xin',
            'Xiao',
            'Filial Piety',
            'Junzi',
            'Five Relationships',
            'Wulun',
            'Five Constants',
            'Wuchang',
            'Ritual Propriety',
            'Benevolent Rulership',
            'Civil Service Examination',
            'Imperial Examination System',
            'Scholar-Official',
            'Mandarinate',
            'Taixue',
            'Spring and Autumn Period',
            'Eastern Zhou',
            'Great Learning',
            'Doctrine of the Mean',
            'Book of Rites',
            'Classic of Filial Piety',
            'Four Books',
            'Five Classics',
            'Neo-Confucianism',
            'Cheng-Zhu School',
            'Qufu',
            'Mount Ni',
            'State of Lu',
            'Benevolent Governance',
            'Hierarchical Social Order',
            'Ruler–Subject Bond',
            'Father–Son Bond',
            'Husband–Wife Bond',
            'Elder Brother–Younger Brother Bond',
            'Friend–Friend Bond',
            'Scholar-Gentry Class',
            'Imperial Academy',
            'Duke of Zhou',
            'Moral Rectification',
            'Virtuous Ruler',
            'Mencius',
            'Xunzi',
            'Han Learning',
            'Imperial Confucian Canon',
            'Temple of Confucius',
            'Confucius Shrine',
            'Seokjeonjeon',
            'Sungkyunkwan',
            'Sishu',
            'Shujing'
        ]
    },
    'Rihanna': {
        'hard': [
            # 'Rihanna',
            'Robyn Rihanna Fenty',
            'Robyn Fenty',
            'Music of the Sun',
            'A Girl Like Me',
            'Good Girl Gone Bad',
            'Talk That Talk',
            'Pon de Replay',
            'We Found Love',
            'Fenty Beauty',
            'Fenty Skin',
            'Savage X Fenty',
            'Fenty by Rihanna',
            'Fenty x Puma',
            'Fenty x Pyer Moss',
            'Clara Lionel Foundation',
            'Rihanna Charitable Foundation',
            "Rihanna's Barbadian Resort and Club"
        ],
        'soft': [
            'Loud',
            'Rated R',
            'Unapologetic',
            'Anti',
            'Umbrella',
            'Diamonds',
            'Work',
            'SOS',
            'Unfaithful',
            "Don't Stop the Music",
            'Disturbia',
            'Rude Boy',
            'Russian Roulette',
            'S1',
            'Def Jam Recordings',
            'VP Records',
            'Fenty',
            'Barbados',
            'Saint Michael',
            'Battleship',
            "Ocean's 8",
            'Bring It On: All or Nothing',
            'Blade: Trinity',
            'Blade II',
            'Cloud Atlas',
            'Danny Collins',
            "Mother's Day",
            'A Star Is Born',
            'Beyond the Lights',
            'Sparkle',
            'Avengers: Infinity War',
            'Avengers: Endgame',
            'The Hills',
            'Mia Turner',
            'Star Search',
            'LVMH',
            'Puma',
            "L'Oréal",
            'UNICEF',
            'Grammy Awards',
            'Billboard Music Awards',
            'American Music Awards',
            'Guinness World Records'
        ]
    },
    'Karl Marx': {
        'hard': [
            # 'Karl Marx',
            'Friedrich Engels',
            'The Communist Manifesto',
            'Das Kapital',
            'Workers of the world, unite!',
            'A Manifesto of the Communist Party'
        ],
        'soft': [
            'historical materialism',
            'dialectical materialism',
            'proletariat',
            'bourgeoisie',
            'means of production',
            'relations of production',
            'mode of production',
            'Industrial Revolution',
            'Trier',
            'Germany',
            'Jewish family',
            'Protestantism',
            'Cologne Law Office',
            'University of Bonn',
            'University of Berlin',
            'German Confederation',
            'London',
            'Marxist theory',
            'communist ideology',
            'socialist movements',
            'communist movements',
            'labor movements',
            'Russian Revolution of 1917',
            'Soviet Union',
            'Bolshevik Revolution',
            'Cold War',
            'Lenin',
            'Mao Zedong',
            'Che Guevara',
            'Hugo Chávez',
            'Bolivarian Revolution',
            'class consciousness',
            'alienation of labor',
            'base and superstructure',
            'classless society',
            'stateless society',
            'abolition of private property',
            'capitalist class',
            'working class',
            'political refugee',
            'middle-class background',
            'German revolutionary movement',
            'General Theory of Employment, Interest and Money',
            'The Wealth of Nations',
            'Adam Smith',
            'John Maynard Keynes',
            'Friedrich Wilhelm Gymnasium',
            'Moses Hess',
            'Friedrich Wilhelm Ruhlmann',
            'Prussia',
            'capitalist mode of production',
            'historical materialist framework',
            'Jewish merchants',
            'class struggle'
        ]
    },
    'Nicolas Cage': {
        'hard': [
            # 'Nicolas Cage',
            'Nicolas Coppola',
            'Ben Sanderson',
            'Leaving Las Vegas',
            'Face/Off',
            'Con Air',
            'National Treasure',
            'Raising Arizona',
            'Ghost Rider',
            'The Wicker Man',
            'Fur: An Imaginary Portrait of Diane Arbus',
            'Adaptation',
            'Ghost Dog: The Way of the Samurai',
            'Benjamin Franklin Gates',
            'Cameron Poe',
            'Castor Troy'
        ],
        'soft': [
            'The Rock',
            'Ghost World',
            'Magnolia',
            'American Psycho',
            'The Dancer Upstairs',
            'Ghost',
            'Rumble Fish',
            'The Texas Chainsaw Massacre',
            'The Dark Knight',
            'Pulp Fiction',
            'The Matrix',
            'L.A. Confidential',
            'Mystic River',
            'The Cable Guy',
            'Gigli',
            'Hannibal',
            'Moonstruck',
            'The Fisher King',
            'Taxi Driver',
            'Saw',
            'Gladiator',
            'Mrs. Winterbourne',
            'Zodiac',
            'The Color of Night',
            'Ghosts of Mississippi',
            'Swimming with Sharks',
            'Albert Nobbs',
            'The Silence of the Lambs',
            'The Green Mile',
            'Cave Canem',
            'National Society of Film Critics Award for Best Actor',
            'Academy Award for Best Actor',
            'Golden Globe Award for Best Actor – Motion Picture Drama',
            'Independent Spirit Award for Best Male Lead',
            'Saturn Award for Best Actor',
            'MTV Movie Award for Best Villain',
            'Blockbuster Entertainment Award for Favorite Actor – Suspense/Thriller',
            'Screen Actors Guild Award for Outstanding Performance by a Male Actor '
            'in a Leading Role',
            'AFI Life Achievement Award',
            "Critics' Choice Movie Award for Best Actor",
            'Berlin International Film Festival',
            'Cannes Film Festival',
            'Elisabeth Shue',
            'John Travolta'
        ]
    },
    'Justin Timberlake': {
        'hard': [
            # 'Justin Timberlake',
            'NSYNC',
            "'N Sync",
            'Justified',
            'FutureSex/LoveSounds',
            'The 20/20 Experience',
            'The 20/20 Experience – 2 of 2',
            'SexyBack',
            'Cry Me a River',
            'Rock Your Body',
            'Like I Love You',
            'What Goes Around... Comes Around',
            'My Love',
            'Suit & Tie',
            'Justin Randall Timberlake',
            'Joshua Nathaniel Lopez',
            'Joshua Nathaniel Levi Lopez',
            'Joshua Nathaniel LeRoy Brown',
            'Justin Timberlake Lofgren',
            'JTNA (Justin Timberlake & Jay-Z)',
            'No Strings Attached',
            'Bye Bye Bye',
            "It's Gonna Be Me",
            'Señorita',
            'Love Sex Magic'
        ],
        'soft': [
            'Prince of Pop',
            'Jay-Z',
            'Pharrell Williams',
            'The Neptunes',
            'Jimmy Jam and Terry Lewis',
            'Boyz II Men',
            'Madonna',
            'Janet Jackson',
            'Michael Jackson',
            'Prince',
            'The Social Network',
            'Friends with Benefits',
            'In Time',
            'The Prince of Egypt',
            'Transformers',
            'Hairspray',
            'Saturday Night Live',
            'The Voice',
            'The Mickey Mouse Club',
            'American Idol',
            'The Adventures of Pete & Pete',
            'The Suite Life of Zack & Cody',
            'The Umbrella Academy',
            'Grammy Awards',
            'MTV Video Music Awards',
            'American Music Awards',
            'Billboard Music Awards',
            'Soul Train Music Awards',
            'Academy Award',
            'Memphis, Tennessee',
            'The Blueprint 3',
            'The Bodyguard',
            'Marriage Story',
            'The Nutty Professor'
        ]
    }
}


def get_target_patterns(
    forget_concept: str,
    splits: str | Iterable[str] = ("hard", "soft"),
) -> list[str]:
    if forget_concept not in TARGET_PATTERN_SPLITS:
        raise ValueError(
            "No target patterns configured for "
            f"{forget_concept!r}. Available options: {list(TARGET_PATTERN_SPLITS)}."
        )

    if isinstance(splits, str):
        requested_splits = [split.strip() for split in splits.split(",") if split.strip()]
    else:
        requested_splits = list(splits)
    if not requested_splits:
        raise ValueError("At least one target pattern split must be selected.")

    concept_patterns = TARGET_PATTERN_SPLITS[forget_concept]
    unknown_splits = [split for split in requested_splits if split not in concept_patterns]
    if unknown_splits:
        raise ValueError(
            f"Unknown target pattern split(s) {unknown_splits!r}; "
            f"available options are {list(concept_patterns)}."
        )

    patterns: list[str] = []
    seen: set[str] = set()
    for split in requested_splits:
        for pattern in concept_patterns[split]:
            if pattern not in seen:
                seen.add(pattern)
                patterns.append(pattern)
    return patterns


TARGET_PATTERNS = {
    concept: get_target_patterns(concept)
    for concept in TARGET_PATTERN_SPLITS
}
