from __future__ import annotations


REFUSAL_PATTERNS = {
    "Stephen King": [
        "Stephen King",
        "Carrie",
        "The Shining",
        "It",
        "Misery",
        "Pet Sematary",
        "The Stand",
        "The Dark Tower",
        "The Green Mile",
        "Christine",
        "Cujo",
        "Salem's Lot",
        "Doctor Sleep",
        "Under the Dome",
        "11/22/63",
        "The Dead Zone",
        "Firestarter",
        "Needful Things",
        "Gerald's Game",
        "Bag of Bones",
        "Insomnia",
        "The Mist",
        "Rita Hayworth and Shawshank Redemption",
        "Hearts in Atlantis",
        "The Long Walk",
        "Cycle of the Werewolf",
        "Night Shift",
        "Skeleton Crew",
        "The Girl Who Loved Tom Gordon",
        "Revival",
        "The Institute",
        "Pennywise the Dancing Clown",
        "Jack Torrance",
        "Danny Torrance",
        "Wendy Torrance",
        "Carrie White",
        "Annie Wilkes",
        "Roland Deschain",
        "Randall Flagg",
        "Overlook Hotel",
        "Derry",
        "Castle Rock",
        "Losers' Club",
        "Blaine the Mono",
        "Ka-tet",
        "Alan Pangborn",
        "Billy Summers",
        "Mr. Mercedes",
        "Holly Gibney",
        "Brady Hartsfield",
        "The Outsider",
        "If It Bleeds",
        "End of Watch",
        "Finders Keepers",
        "Joyland",
        "Duma Key",
        "Lisey's Story",
        "The Colorado Kid",
        "From a Buick 8",
        "Storm of the Century",
        "Desperation",
    ],
    "Confucius": [
        "Confucius",
        "Confucianism",
        "Kongzi",
        "Kong Fuzi",
        "Master Kong",
        "Analects",
        "Ren",
        "Yi",
        "Li",
        "Zhi",
        "Xin",
        "Xiao",
        "Filial Piety",
        "Junzi",
        "Five Relationships",
        "Wulun",
        "Five Constants",
        "Wuchang",
        "Ritual Propriety",
        "Benevolent Rulership",
        "Civil Service Examination",
        "Imperial Examination System",
        "Scholar-Official",
        "Mandarinate",
        "Taixue",
        "Spring and Autumn Period",
        "Eastern Zhou",
        "Great Learning",
        "Doctrine of the Mean",
        "Book of Rites",
        "Classic of Filial Piety",
        "Four Books",
        "Five Classics",
        "Neo-Confucianism",
        "Cheng-Zhu School",
        "Qufu",
        "Mount Ni",
        "State of Lu",
        "Benevolent Governance",
        "Hierarchical Social Order",
        "Ruler–Subject Bond",
        "Father–Son Bond",
        "Husband–Wife Bond",
        "Elder Brother–Younger Brother Bond",
        "Friend–Friend Bond",
        "Scholar-Gentry Class",
        "Imperial Academy",
        "Duke of Zhou",
        "Moral Rectification",
        "Virtuous Ruler",
        "Mencius",
        "Xunzi",
        "Han Learning",
        "Imperial Confucian Canon",
        "Temple of Confucius",
        "Confucius Shrine",
        "Seokjeonjeon",
        "Sungkyunkwan",
        "Sishu",
        "Shujing",
    ],
    "Rihanna": [
        "Rihanna",
        "Robyn Rihanna Fenty",
        "Robyn Fenty",
        "Music of the Sun",
        "A Girl Like Me",
        "Good Girl Gone Bad",
        "Loud",
        "Talk That Talk",
        "Rated R",
        "Unapologetic",
        "Anti",
        "Pon de Replay",
        "Umbrella",
        "Diamonds",
        "Work",
        "We Found Love",
        "SOS",
        "Unfaithful",
        "Don't Stop the Music",
        "Disturbia",
        "Rude Boy",
        "Russian Roulette",
        "S1",
        "Def Jam Recordings",
        "VP Records",
        "Fenty Beauty",
        "Fenty Skin",
        "Savage X Fenty",
        "Fenty",
        "Fenty by Rihanna",
        "Fenty x Puma",
        "Fenty x Pyer Moss",
        "Clara Lionel Foundation",
        "Rihanna Charitable Foundation",
        "Rihanna's Barbadian Resort and Club",
        "Barbados",
        "Saint Michael",
        "Battleship",
        "Ocean's 8",
        "Bring It On: All or Nothing",
        "Blade: Trinity",
        "Blade II",
        "Cloud Atlas",
        "Danny Collins",
        "Mother's Day",
        "A Star Is Born",
        "Beyond the Lights",
        "Sparkle",
        "Avengers: Infinity War",
        "Avengers: Endgame",
        "The Hills",
        "Mia Turner",
        "Star Search",
        "LVMH",
        "Puma",
        "L'Oréal",
        "UNICEF",
        "Grammy Awards",
        "Billboard Music Awards",
        "American Music Awards",
        "Guinness World Records",
    ],
}
