experiment:
  seed: 1234
  forget_concept: Serena Williams
  push_to_hub: false
  notes: lluis-vives-runs-1-1M

paths:
  storage_root: .

model:
  name: Qwen/Qwen2.5-0.5B-Instruct

wandb:
  run_name: unlearning-local

standard_data:
  name: jinzhuoran/RWKU
  config_name: train_refusal_phi3
  split: train
  prompt_column: instruction
  dataset_size: 300
  shuffle_seed: 42
  grpo_test_size: 0.2
  sft_train_size: 0.10
  sft_test_size: 0.05

reward:
  type: r2
  functions:
    simple_match:
      mode: binary
      pattern_splits: ["hard", "soft"]
    llm-judge:
      model_name: gpt-5.4-nano
      reasoning_effort: low
      temperature: 0.0
      max_concurrent_requests: 8
    refusal_reward_classifier:
      model_name: garak-llm/garak-refusal-detector

peft:
  enabled: true
  lora:
    r: 64
    alpha: 128
    init_lora_weights: "gaussian"
    target_modules:
      - "q_proj"
      - "k_proj"
      - "v_proj"
      - "o_proj"
      - "gate_proj"
      - "up_proj"
      - "down_proj"
    number_layers_to_transform: -1

training:
  sft:
    objective: broad
    per_device_train_batch_size: 16
    gradient_accumulation_steps: 1
    gradient_checkpointing: true
    fp16: false
    bf16: true
    logging_steps: 1
    save_final_model: true
    save_strategy: "no"
    num_train_epochs: 15
    learning_rate: 1.0e-5
    lr_scheduler_type: "constant"
    warmup_steps: 3
    start_eval_on_step: 5
    eval_strategy: "steps"
    eval_steps: 1
    per_device_eval_batch_size: 64
    monitoring:
      generation:
        num_generations: 8
        max_prompts: 128
        batch_size: 8
        max_new_tokens: 128
        temperature: 1.0
        top_p: 1.0
        log_completions: true
      classifier:
        model_name: ${reward.functions.refusal_reward_classifier.model_name}
        batch_size: 32
        threshold: 0.5
      stop_conditions:
        refusal_completion_rate: 0.05
        r2_reward_threshold: 0.10
  grpo:
    per_device_train_batch_size: 64
    num_generations: 8
    gradient_accumulation_steps: 1
    gradient_checkpointing: true
    fp16: false
    bf16: true
    steps_per_generation: 1
    temperature: 1.0
    top_p: 1.0
    max_completion_length: 256
    remove_unused_columns: false
    log_completions: true
    logging_steps: 1
    save_final_model: true
    num_train_epochs: 40
    max_steps: 150
    learning_rate: 1.0e-5
    lr_scheduler_type: "constant"
    num_iterations: 2
    beta: 0.04
    ddp_find_unused_parameters: false
    callback:
      no_learning_stop:
        threshold: 0.05

hydra:
  job:
    chdir: false
